# DigitalOcean App Platform Spec
name: "webinar-1755614982050"
region: nyc
static_sites:
  - name: presentation
    github:
      repo: ElanHasson/1755614982050
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: out
    routes:
      - path: /
    environment_slug: node-js
